[2] - Elasticsearch and Kibana added to Docker
LeWricka/PrAnalytics pull request #5
Opened 2020-01-12 12:10 UTC by wricka

2020-01-12 12:11 UTC, LeWricka requested changes

2020-01-12 12:11 UTC, LeWricka commented on docker-compose-prod.yml
> +      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
[Testing] - Testing comment

2020-01-12 12:11 UTC, LeWricka commented on docker-compose.yml
> +    elasticsearch:
[Naming] - Naming comment

2020-01-17 20:20 UTC, wricka commented on docker-compose.yml
> +        - node.name=elasticsearch1
[Architecture]: Is this correct?

2020-01-17 20:20 UTC, wricka commented on src/Infrastructure/Controller/AddCommentController.php
> +        $request = Request::createFromGlobals();
[Testing]: Another testing comment

2020-01-17 20:20 UTC, wricka commented on docker-compose-prod.yml
> +      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
ok

2020-01-17 20:30 UTC, LeWricka approved these changes
Ok to merge

2020-01-17 20:30 UTC, merged